apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "websight-ce.fullname" . }}-mongo-repository
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
