apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "websight-ce.fullname" . }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "websight-ce.name" . }}-mongo
      app.kubernetes.io/instance: {{ .Release.Name }}-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "websight-ce.name" . }}-mongo
        app.kubernetes.io/instance: {{ .Release.Name }}-mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongoadmin
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
          image: {{ .Values.mongo.image }}
          name: mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: {{ .Values.mongo.resources.requests.memory }}
              cpu: {{ .Values.mongo.resources.requests.cpu }}
            limits:
              memory: {{ .Values.mongo.resources.limits.memory }}
              cpu: {{ .Values.mongo.resources.limits.cpu }}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-repository
      restartPolicy: Always
      volumes:
        - name: mongo-repository
          persistentVolumeClaim:
            claimName: {{ include "websight-ce.fullname" . }}-mongo-repository
status: {}
