apiVersion: v1
kind: Service
metadata:
  name: {{ include "websight-ce.fullname" . }}-nginx
spec:
  ports:
    - port: {{ .Values.nginx.ports.http }}
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "websight-ce.name" . }}-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}-nginx
