apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "websight-ce.fullname" . }}-cms-logs
  labels:
    app.kubernetes.io/name: {{ include "websight-ce.name" . }}-cms
    app.kubernetes.io/instance: {{ .Release.Name }}-cms
    app.kubernetes.io/version: {{ .Values.cms.image.tag }}
    app.kubernetes.io/websight-version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: cms
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
