apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "websight-ce.fullname" . }}-cms-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
