apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "websight-ce.fullname" . }}-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "websight-ce.name" . }}-cms
      app.kubernetes.io/instance: {{ .Release.Name }}-cms
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "websight-ce.name" . }}-cms
        app.kubernetes.io/instance: {{ .Release.Name }}-cms
    spec:
      containers:
        - env:
            - name: LEASE_CHECK_MODE
              value: LENIENT
            - name: MONGODB_HOST
              value: {{ include "websight-ce.fullname" . }}-mongo
            - name: MONGODB_PORT
              value: "27017"
            - name: WS_ADMIN_PASSWORD
              value: wsadmin
            - name: WS_ADMIN_USERNAME
              value: wsadmin
          image: {{ .Values.cms.image }}
          name: cms
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ .Values.cms.resources.requests.memory }}
              cpu: {{ .Values.cms.resources.requests.cpu }}
            limits:
              memory: {{ .Values.cms.resources.limits.memory }}
              cpu: {{ .Values.cms.resources.limits.cpu }}
          volumeMounts:
            - mountPath: /websight/logs
              name: cms-logs
            - mountPath: /websight/docroot
              name: site-repository
      restartPolicy: Always
      volumes:
        - name: cms-logs
          persistentVolumeClaim:
            claimName: {{ include "websight-ce.fullname" . }}-cms-logs
        - name: site-repository
          persistentVolumeClaim:
            claimName: {{ include "websight-ce.fullname" . }}-site-repository
status: {}
