apiVersion: v1
kind: Service
metadata:
  name: {{ include "websight-ce.fullname" . }}-cms
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cms.ports.admin }}
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "websight-ce.name" . }}-cms
    app.kubernetes.io/instance: {{ .Release.Name }}-cms
