apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "websight-ce.fullname" . }}-site-repository
  labels:
    app.kubernetes.io/name: {{ include "websight-ce.name" . }}-site-repository
    app.kubernetes.io/instance: {{ .Release.Name }}-site-repository
    app.kubernetes.io/websight-version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "site-repository"
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  {{- if le (add .Values.cms.replicas .Values.nginx.replicas) 2 }}
    - ReadWriteOnce
  {{ else }}
    - ReadWriteMany
  {{ end -}}
  resources:
    requests:
      storage: {{ .Values.siteRepository.storage.size }}
